# permissions to do viewer cloudfoundries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudfoundry-viewer-role
rules:
- apiGroups:
  - runtime.circle.example.com
  resources:
  - cloudfoundries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - runtime.circle.example.com
  resources:
  - cloudfoundries/status
  verbs:
  - get
