# permissions for end users to view orgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: org-viewer-role
rules:
- apiGroups:
  - cf.circle.example.com
  resources:
  - orgs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cf.circle.example.com
  resources:
  - orgs/status
  verbs:
  - get
