# permissions for end users to edit orgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: org-editor-role
rules:
- apiGroups:
  - cf.circle.example.com
  resources:
  - orgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cf.circle.example.com
  resources:
  - orgs/status
  verbs:
  - get
